---
- name: install and configure springboot 
  hosts: appserver
  become: yes
  vars:
    java_package: openjdk-11-jdk
    user_name: springbootuser
    app_home: /usr/share/springpetclinic
    app_path: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
  tasks:
    - name: update packages & install java_package
      apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
    - name: create springpetclinic directory
      file:
        path: "{{ app_home }}"
        state: directory    
    - name: download spring petclinic
      get_url:
        url: https://referenceapplicationskhaja.s3.us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
        dest: "{{ app_path }}"
    - name: add user  
      ansible.builtin.user:
        name: "{{ user_name }}"
        password: "{{ user_name }}"
        state: present
    - name: Recursively change ownership of a directory
      ansible.builtin.file:
        path: spc /usr/share/spc/spring-petclinic.jar
        state: directory   
        recurse: yes
        group: "{{ user_name }}"
        owner: root
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: "{{ app_path}}"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '500'    
    - name: Copy the spring petclinic service file
      ansible.builtin.copy:
        src: springpetclinic.service
        dest: /etc/systemd/system/springpetclinic.service 
        remote_src: yes 
    - name: Enable and start spring petclinic
      ansible.builtin.systemd:
        name: springpetclinic.service
        enabled: yes
        state: started       