---
- name: install and configure springboot 
  hosts: appserver
  become: yes
  vars:
    java_package: openjdk-11-jdk
    app_username: springuser
    app_home: /usr/share/springpetclinic
    app_path: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
  tasks:
    - name: update packages & install java_package
      apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
    - name: create springpetclinic directory
      file:
        path: "{{ app_home }}"
        state: directory    
    - name: download the springpetclinic file
      get_url:
        url: https://referenceapplicationskhaja.s3.us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
        dest: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
    - name: add user 
      ansible.builtin.user:
        name: "{{ app_username }}"
        password: "{{ app_username }}"
        state: present
    - name: Recursively change ownership of a directory
      ansible.builtin.file:
        path: "{{ app_path}}"
        state: directory
        recurse: yes
        owner: "{{ app_username }}"
        group: "{{ app_username }}"
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: "{{ app_path}}"
        owner: "{{ app_username }}"
        group: "{{ app_username }}"
        mode: '500'    
        state: file
    - name: configure springpetclinic service
      ansible.builtin.copy:
        src: springboot.service
        dest: /etc/systemd/system/springpetclinic.service 
  handlers:
    - name: springpetclinic.service
      ansible.builtin.systemd:
        name: springpetclinic.service
        enabled: yes
        state: started       