---
- name: install and configure springboot 
  hosts: appserver
  become: yes
  vars:
    java_package: openjdk-11-jdk
    springboot_username: springboot
    springboot_home: /usr/share/springpetclinic
    spring-petclinic_path: /usr/share/springpetclinic
  tasks:
    - name: update packages & install java_package
      apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
    - name: add springboot user 
      ansible.builtin.user:
        name: "{{ springboot_username }}"
        home: "{{ springboot_home }}"
        state: present
    - name: download the springbootfile
      get_url:
        url: https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
        dest: "{{ spring-petclinic_path }}"
        state: present
    - name: Recursively change ownership of a directory
      ansible.builtin.file:
        path: "{{ springboot_home }}"
        state: directory
        recurse: yes
        owner: "{{ springboot_username }}"
        group: "{{ springboot_username }}"
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: "{{ springboot_home }}"
        owner: "{{ springboot_username }}"
        group: "{{ springboot_username }}"
        mode: '500'    
    - name: configure springboot service
      ansible.builtin.copy:
        src: springboot.service
        dest: /etc/systemd/system/springpetclinic.service 
  handlers:
    - name: springpetclinic.service
      ansible.builtin.systemd:
        name: springpetclinic.service
        enabled: yes
        state: started       